import React from 'react'
import Head from 'next/head';
import Master from '../../components/layouts/Master';

const create = () => {
    return (
        <>
            <Head>
                <title>Create</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Master>
                <div className="app-content pt-3 p-md-3 p-lg-4">
                    <div className="container-xl">

                        <h1 className="app-page-title">Order</h1>
                    </div>
                </div>
            </Master>
        </>
    )
}

export default create
