import React, { useEffect, useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import Master from '../components/layouts/Master';
import Card from '../components/home/Card';

const Home = () => {
  const router = useRouter();
  const [cardDetails] = useState([
    {
      type: 'Total Sales',
      figure: '12,628'
    },
    {
      type: 'Expenses',
      figure: '2,250'
    },
    {
      type: 'Projects',
      figure: '23'
    },
    {
      type: 'Invoices',
      figure: '6'
    }
  ]);


  useEffect(() => {
    if (!localStorage.getItem('user')) router.push("login");
  }, []);

  return (
    <>
      <Head>
        <title>Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Master>
        <div className="app-content pt-3 p-md-3 p-lg-4">
          <div className="container-xl">
            <h1 className="app-page-title">Overview</h1>
          </div>
          <div className="row g-4 mb-4">
            {cardDetails.map((details, key) => <Card key={key} {...details} />)}
          </div>
        </div>
      </Master>
    </>
  )
}



export default Home;
